(eval-when-compile    (require 'color-theme))

(defun paul-themes-default ()
  "Color theme by Paul Ozog, created 2015-10-12."
  (interactive)
  (color-theme-install
   '(paul-themes-default
     ((background-color . "white")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "black")
      (mouse-color . "black"))
     ((ac-fuzzy-cursor-color . "red")
      (browse-kill-ring-current-entry-face . highlight)
      (browse-kill-ring-inserted-item-face . highlight)
      (browse-kill-ring-separator-face . bold)
      (compilation-message-face . underline)
      (fci-rule-color . "#cccccc")
      (highline-face . highline-face)
      (highline-vertical-face . highline-vertical-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown" :family "Ubuntu Mono"))))
     (ac-candidate-face ((t (:foreground "black" :background "lightgray"))))
     (ac-candidate-mouse-face ((t (:foreground "white" :background "blue"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:foreground "white" :background "navy"))))
     (ac-selection-face ((t (:foreground "white" :background "steelblue"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:foreground "white" :background "coral3"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "RoyalBlue3"))))
     (calendar-today ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "medium blue"))))
     (compilation-column-number ((t (:foreground "VioletRed4"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red1"))))
     (compilation-info ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (compilation-line-number ((t (:foreground "Purple"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "black"))))
     (diary ((t (:foreground "red1"))))
     (diff-file1-hunk-header ((t (:background "DarkSeaGreen1" :foreground "Blue"))))
     (diff-file2-hunk-header ((t (:background "PaleGoldenrod" :foreground "Red"))))
     (diff-indicator-added ((t (:background "DarkGreen" :foreground "PaleGoldenrod"))))
     (diff-indicator-changed ((t (:background "MediumBlue" :foreground "PaleGoldenrod"))))
     (diff-indicator-removed ((t (:background "DarkMagenta" :foreground "PaleGoldenrod"))))
     (dired-directory ((t (:foreground "dark slate blue"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-header ((t (:foreground "ForestGreen"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "dark cyan"))))
     (dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (dired-perm-write ((t (:foreground "Firebrick"))))
     (dired-symlink ((t (:foreground "Firebrick"))))
     (dired-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (error ((t (:bold t :foreground "Red1" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (etags-select-highlight-tag-face ((t (:bold t :background "cadetblue4" :foreground "white" :weight bold))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:bold t :weight bold :foreground "Red1"))))
     (flymake-warnline ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (font-lock-builtin-face ((t (:foreground "dark slate blue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "Firebrick"))))
     (font-lock-comment-face ((t (:foreground "Firebrick"))))
     (font-lock-constant-face ((t (:foreground "dark cyan"))))
     (font-lock-doc-face ((t (:foreground "VioletRed4"))))
     (font-lock-function-name-face ((t (:foreground "Blue1"))))
     (font-lock-keyword-face ((t (:foreground "Purple"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "dark slate blue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "VioletRed4"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:foreground "sienna"))))
     (font-lock-warning-face ((t (:bold t :weight bold :foreground "Red1"))))
     (fringe ((t (:background "grey95"))))
     (glyphless-char ((t (:height 0.6))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkseagreen2"))))
     (highline-face ((t (:background "#EEEEEE"))))
     (highline-vertical-face ((t (:background "yellow1"))))
     (holiday ((t (:background "pink"))))
     (idle-highlight ((t (:bold t :foreground "#ff0000" :weight bold))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Red1" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "dark slate blue"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
     (info-header-xref ((t (:foreground "RoyalBlue3" :underline t))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:underline t :foreground "RoyalBlue3"))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "RoyalBlue3" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (linum ((t (:foreground "grey50"))))
     (markdown-blockquote-face ((t (:foreground "VioletRed4"))))
     (markdown-bold-face ((t (:bold t :foreground "sienna" :weight bold))))
     (markdown-comment-face ((t (:foreground "Firebrick"))))
     (markdown-footnote-face ((t (:weight normal :slant normal :foreground "grey50"))))
     (markdown-gfm-checkbox-face ((t (:foreground "dark slate blue"))))
     (markdown-header-delimiter-face ((t (:weight normal :slant normal :foreground "grey50"))))
     (markdown-header-face ((t (:bold t :foreground "Blue1" :weight bold))))
     (markdown-header-face-1 ((t (:bold t :weight bold :foreground "Blue1"))))
     (markdown-header-face-2 ((t (:bold t :weight bold :foreground "Blue1"))))
     (markdown-header-face-3 ((t (:bold t :weight bold :foreground "Blue1"))))
     (markdown-header-face-4 ((t (:bold t :weight bold :foreground "Blue1"))))
     (markdown-header-face-5 ((t (:bold t :weight bold :foreground "Blue1"))))
     (markdown-header-face-6 ((t (:bold t :weight bold :foreground "Blue1"))))
     (markdown-header-rule-face ((t (:weight normal :slant normal :foreground "grey50"))))
     (markdown-highlight-face ((t (:background "darkseagreen2"))))
     (markdown-inline-code-face ((t (:foreground "dark cyan"))))
     (markdown-italic-face ((t (:italic t :foreground "sienna" :slant italic))))
     (markdown-language-keyword-face ((t (:foreground "ForestGreen"))))
     (markdown-line-break-face ((t (:foreground "dark cyan" :underline t))))
     (markdown-link-face ((t (:foreground "Purple"))))
     (markdown-link-title-face ((t (:foreground "Firebrick"))))
     (markdown-list-face ((t (:weight normal :slant normal :foreground "grey50"))))
     (markdown-markup-face ((t (:foreground "grey50" :slant normal :weight normal))))
     (markdown-math-face ((t (:foreground "VioletRed4"))))
     (markdown-metadata-key-face ((t (:foreground "sienna"))))
     (markdown-metadata-value-face ((t (:foreground "VioletRed4"))))
     (markdown-missing-link-face ((t (:bold t :foreground "Red1" :weight bold))))
     (markdown-pre-face ((t (:foreground "dark cyan"))))
     (markdown-reference-face ((t (:weight normal :slant normal :foreground "grey50"))))
     (markdown-strike-through-face ((t (:foreground "sienna" :strike-through t))))
     (markdown-url-face ((t (:foreground "VioletRed4"))))
     (match ((t (:background "yellow1"))))
     (matlab-cellbreak-face ((t (:bold t :foreground "Firebrick" :overline t :weight bold))))
     (matlab-cross-function-variable-face ((t (:italic t :bold t :slant italic :weight bold))))
     (matlab-nested-function-keyword-face ((t (:italic t :slant italic))))
     (matlab-region-face ((t (:background "gtk_selection_bg_color" :foreground "gtk_selection_fg_color"))))
     (matlab-simulink-keyword-face ((t (:foreground "ForestGreen" :underline t))))
     (matlab-unterminated-string-face ((t (:foreground "VioletRed4" :underline t))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (nil))))
     (next-error ((t (:foreground "gtk_selection_fg_color" :background "gtk_selection_bg_color"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (org-agenda-calendar-event ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 98))))
     (org-agenda-calendar-sexp ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 98))))
     (org-agenda-clocking ((t (:background "yellow1"))))
     (org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "#000000" :height 98))))
     (org-agenda-current-time ((t (:foreground "DarkGoldenrod"))))
     (org-agenda-date ((t (:foreground "Blue1"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-agenda-diary ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 98))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "ForestGreen"))))
     (org-agenda-filter-category ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-filter-tags ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-restriction-lock ((t (:background "yellow1"))))
     (org-agenda-structure ((t (:foreground "Blue1"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-block ((t (:foreground "grey50"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:foreground "Firebrick"))))
     (org-block-end-line ((t (:foreground "Firebrick"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Red1"))))
     (org-clock-overlay ((t (:background "yellow1"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "#000000" :strike-through nil :underline nil :slant normal :weight normal :height 98 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "Purple" :underline t))))
     (org-date-selected ((t (:background "Red1"))))
     (org-default ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 98))))
     (org-document-info ((t (:foreground "midnight blue"))))
     (org-document-info-keyword ((t (:foreground "grey50"))))
     (org-document-title ((t (:bold t :foreground "midnight blue" :weight bold))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "Blue1"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Purple" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-headline-done ((t (:foreground "RosyBrown"))))
     (org-hide ((t (:foreground "white"))))
     (org-latex-and-export-specials ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:foreground "Blue1"))))
     (org-level-2 ((t (:foreground "sienna"))))
     (org-level-3 ((t (:foreground "Purple"))))
     (org-level-4 ((t (:foreground "Firebrick"))))
     (org-level-5 ((t (:foreground "ForestGreen"))))
     (org-level-6 ((t (:foreground "dark cyan"))))
     (org-level-7 ((t (:foreground "dark slate blue"))))
     (org-level-8 ((t (:foreground "VioletRed4"))))
     (org-link ((t (:underline t :foreground "RoyalBlue3"))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-meta-line ((t (:foreground "Firebrick"))))
     (org-mode-line-clock ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-mode-line-clock-overrun ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "red"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey50"))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "Firebrick"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "Purple"))))
     (org-table ((t (:foreground "Blue1"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-verse ((t (:foreground "grey50"))))
     (org-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (outline-1 ((t (:foreground "Blue1"))))
     (outline-2 ((t (:foreground "sienna"))))
     (outline-3 ((t (:foreground "Purple"))))
     (outline-4 ((t (:foreground "Firebrick"))))
     (outline-5 ((t (:foreground "ForestGreen"))))
     (outline-6 ((t (:foreground "dark cyan"))))
     (outline-7 ((t (:foreground "dark slate blue"))))
     (outline-8 ((t (:foreground "VioletRed4"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:foreground "black" :background "lightgray"))))
     (popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-summary-face ((t (:foreground "dimgray" :background "lightgray"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-summary-face ((t (:background "lightgray" :foreground "dimgray"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "gtk_selection_bg_color" :foreground "gtk_selection_fg_color"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow1"))))
     (sh-escaped-newline ((t (:foreground "VioletRed4"))))
     (sh-heredoc ((t (:foreground "tan1"))))
     (sh-quoted-exec ((t (:foreground "magenta"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (success ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:foreground "gtk_selection_fg_color" :background "gtk_selection_bg_color")))))))
(add-to-list 'color-themes '(paul-themes-default  "Default" "Paul Ozog <pjozog@gmail.com>"))

(defun paul-themes-naquadah2 ()
  "Color theme by Paul Ozog, created 2015-10-12."
  (interactive)
  (color-theme-install
   '(paul-themes-naquadah2
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "red")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     ((ac-fuzzy-cursor-color . "red")
      (browse-kill-ring-current-entry-face . highlight)
      (browse-kill-ring-inserted-item-face . highlight)
      (browse-kill-ring-separator-face . bold)
      (compilation-message-face . underline)
      (fci-rule-color . "#cccccc")
      (highline-face . highline-face)
      (highline-vertical-face . highline-vertical-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (widget-mouse-face . highlight))
     (ac-candidate-face ((t (:foreground "black" :background "lightgray"))))
     (ac-candidate-mouse-face ((t (:foreground "white" :background "blue"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:foreground "white" :background "navy"))))
     (ac-selection-face ((t (:foreground "white" :background "steelblue"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:foreground "white" :background "coral3"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:foreground "#729fcf"))))
     (calendar-today ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (nil))))
     (compilation-column-number ((t (:foreground "#f57900"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
     (compilation-line-number ((t (:bold t :weight bold :foreground "#729fcf"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeec" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "red"))))
     (custom-documentation ((t (:italic t :slant italic :foreground "#BD4BC4"))))
     (custom-face-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (custom-group-tag ((t (:bold t :foreground "#f57900" :weight bold :height 1.3))))
     (custom-state ((t (:foreground "#729fcf"))))
     (custom-variable-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
     (diary ((t (:foreground "yellow1"))))
     (diff-added ((t (:foreground "#73d216"))))
     (diff-changed ((t (:foreground "#fcaf3e"))))
     (diff-file-header ((t (:foreground "#eeeeec"))))
     (diff-file1-hunk-header ((t (:background "#3E3E00003E3E" :foreground "Yellow"))))
     (diff-file2-hunk-header ((t (:background "#111117175555" :foreground "Cyan"))))
     (diff-function ((t (:foreground "#fcaf3e"))))
     (diff-header ((t (:background "#2e3436"))))
     (diff-hunk-header ((t (:bold t :weight bold))))
     (diff-indicator-added ((t (:background "#FFFF9B9BFFFF" :foreground "#111117175555"))))
     (diff-indicator-changed ((t (:background "Yellow" :foreground "#111117175555"))))
     (diff-indicator-removed ((t (:background "#7474FFFF7474" :foreground "#111117175555"))))
     (diff-refine-change ((t (:background "#2e3436"))))
     (diff-removed ((t (:foreground "#ef2929"))))
     (dired-directory ((t (:foreground "#729fcf"))))
     (dired-file-name ((t (:bold t :foreground "white" :weight bold))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-header ((t (:bold t :weight bold :foreground "#73d216"))))
     (dired-ignored ((t (:foreground "#babdb6"))))
     (dired-mark ((t (:foreground "#73d216"))))
     (dired-marked ((t (:bold t :foreground "#fce94f" :weight bold))))
     (dired-perm-write ((t (:italic t :foreground "#BD4BC4" :slant italic))))
     (dired-symlink ((t (:italic t :bold t :slant italic :foreground "#FFFFFFFF7474" :weight bold))))
     (dired-warning ((t (:bold t :weight bold :foreground "#fcaf3e"))))
     (diredp-directory ((t (:foreground "#729fcf"))))
     (diredp-file-name ((t (:bold t :foreground "white" :weight bold))))
     (diredp-symlink ((t (:bold t :foreground "#FFFFFFFF7474" :weight bold))))
     (ediff-current-diff-A ((t (:background "#553333" :foreground "white"))))
     (ediff-current-diff-B ((t (:background "#335533" :foreground "white"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "black"))))
     (ediff-even-diff-B ((t (:background "light grey" :foreground "black"))))
     (ediff-fine-diff-A ((t (:background "#aa2222" :foreground "black"))))
     (ediff-fine-diff-B ((t (:background "#22aa22" :foreground "black"))))
     (ediff-odd-diff-A ((t (:background "light grey" :foreground "black"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "black"))))
     (egocentric-face ((t (:bold t :foreground "#ef2929" :weight bold))))
     (ein:cell-input-area ((t (:background "#000000"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :weight bold :foreground "#ef2929"))))
     (erc-direct-msg-face ((t (:bold t :weight bold :foreground "#ef2929"))))
     (erc-fool-face ((t (:foreground "#babdb6"))))
     (erc-header-line ((t (:box (:line-width 1 :color "#2e3436") :foreground "#eeeeec" :background "#0c191C"))))
     (erc-input-face ((t (:foreground "#babdb6"))))
     (erc-keyword-face ((t (:foreground "#fcaf3e"))))
     (erc-my-nick-face ((t (:bold t :weight bold :foreground "#ef2929"))))
     (erc-notice-face ((t (:foreground "#729fcf"))))
     (erc-pal-face ((t (:bold t :foreground "#8ae234" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "#0c191C" :foreground "#eeeeec" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "#d3d7cf" :weight bold))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (etags-select-highlight-tag-face ((t (:bold t :background "cadetblue4" :foreground "white" :weight bold))))
     (file-name-shadow ((t (:foreground "#babdb6"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:bold t :weight bold :foreground "Pink"))))
     (flymake-warnline ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (font-latex-sedate-face ((t (:foreground "#729fcf"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "#BD4BC4"))))
     (font-lock-comment-face ((t (:italic t :foreground "#BD4BC4" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#73d216"))))
     (font-lock-doc-face ((t (:foreground "#f57900"))))
     (font-lock-function-name-face ((t (:bold t :foreground "#edd400" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "#729fcf" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#729fcf"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "#fcaf3e"))))
     (font-lock-type-face ((t (:bold t :foreground "#73d216" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "#ef2929"))))
     (font-lock-warning-face ((t (:bold t :foreground "#fcaf3e" :weight bold))))
     (fringe ((t (:background "#0c191C"))))
     (git-commit-branch-face ((t (:bold t :foreground "#f57900" :weight bold))))
     (git-commit-comment-face ((t (:italic t :slant italic :foreground "#BD4BC4"))))
     (git-commit-known-pseudo-header-face ((t (:bold t :weight bold :foreground "#729fcf"))))
     (git-commit-nonempty-second-line-face ((t (nil))))
     (git-commit-pseudo-header-face ((t (:italic t :slant italic :foreground "#d3d7cf"))))
     (git-commit-summary-face ((t (:bold t :weight bold))))
     (glyphless-char ((t (:height 0.6))))
     (gnus-button ((t (:bold t :foreground "#d3d7cf" :weight bold))))
     (gnus-cite-1 ((t (:foreground "#729fcf"))))
     (gnus-cite-10 ((t (:foreground "#75507b"))))
     (gnus-cite-11 ((t (:foreground "#c17d11"))))
     (gnus-cite-2 ((t (:foreground "#8ae234"))))
     (gnus-cite-3 ((t (:foreground "#fce94f"))))
     (gnus-cite-4 ((t (:foreground "#ad7fa8"))))
     (gnus-cite-5 ((t (:foreground "#e9b96e"))))
     (gnus-cite-6 ((t (:foreground "#fcaf3e"))))
     (gnus-cite-7 ((t (:foreground "#3465a4"))))
     (gnus-cite-8 ((t (:foreground "#73d216"))))
     (gnus-cite-9 ((t (:foreground "#f57900"))))
     (gnus-header-content ((t (:italic t :foreground "#d3d7cf" :slant italic))))
     (gnus-header-from ((t (:bold t :weight bold))))
     (gnus-header-name ((t (:bold t :foreground "#729fcf" :weight bold))))
     (gnus-header-newsgroups ((t (:bold t :weight bold :foreground "#d3d7cf"))))
     (gnus-header-subject ((t (nil))))
     (gnus-header-to ((t (:bold t :foreground "#d3d7cf" :weight bold))))
     (gnus-signature ((t (:italic t :foreground "#babdb6" :slant italic))))
     (gnus-summary-cancelled ((t (:background "#0c191C" :foreground "#fce94f"))))
     (gnus-summary-high-ancient ((t (:foreground "#4e9a06"))))
     (gnus-summary-high-read ((t (:foreground "#8ae234"))))
     (gnus-summary-high-ticked ((t (:foreground "#ef2929"))))
     (gnus-summary-high-unread ((t (:foreground "#eeeeec"))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "#4e9a06" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "#8ae234" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "#ef2929" :slant italic))))
     (gnus-summary-low-unread ((t (:italic t :foreground "#eeeeec" :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "#4e9a06"))))
     (gnus-summary-normal-read ((t (:foreground "#8ae234"))))
     (gnus-summary-normal-ticked ((t (:foreground "#ef2929"))))
     (gnus-summary-normal-unread ((t (:foreground "#eeeeec"))))
     (gnus-summary-selected ((t (:background "#204a87" :foreground "#eeeeec"))))
     (header-line ((t (:background "#0c191C" :foreground "#eeeeec" :box (:line-width 1 :color "#2e3436")))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "#73d216" :foreground "black"))))
     (highline-face ((t (:background "#470000"))))
     (highline-vertical-face ((t (:background "#204a87"))))
     (hl-line ((t (:background "#2e3436"))))
     (holiday ((t (:background "chocolate4"))))
     (idle-highlight ((t (:bold t :foreground "#ff0000" :weight bold))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "#fcaf3e"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "#729fcf"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
     (info-header-xref ((t (:foreground "#729fcf"))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (isearch ((t (:background "magenta3" :foreground "black"))))
     (isearch-fail ((t (:background "RosyBrown1" :foreground "black"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise" :foreground "black"))))
     (link ((t (:foreground "#729fcf"))))
     (link-visited ((t (:foreground "#ad7fa8"))))
     (linum ((t (:foreground "#babdb6"))))
     (magit-diff-add ((t (:foreground "#73d216"))))
     (magit-diff-del ((t (:foreground "#ef2929"))))
     (magit-item-highlight ((t (:background "#2e3436"))))
     (magit-item-mark ((t (:foreground "#fcaf3e"))))
     (magit-log-graph ((t (:foreground "#d3d7cf"))))
     (magit-log-head-label-bisect-bad ((t (:background "#a40000" :box 1))))
     (magit-log-head-label-bisect-good ((t (:background "#73d216" :box 1))))
     (magit-log-head-label-local ((t (:background "#3465a4" :foreground "#eeeeec" :box (:color "#204a87")))))
     (magit-log-head-label-remote ((t (:background "#edd400" :foreground "#2e3436" :box (:color "#c4a000")))))
     (magit-log-head-label-tags ((t (:box 1 :foreground "#2e3436" :background "#4e9a06"))))
     (magit-log-sha1 ((t (:foreground "#ef2929"))))
     (magit-log-tag-label ((t (:background "#4e9a06" :foreground "#2e3436" :box 1))))
     (makefile-space ((t (:background "#5c3566"))))
     (markdown-blockquote-face ((t (:foreground "#f57900"))))
     (markdown-bold-face ((t (:bold t :foreground "#ef2929" :weight bold))))
     (markdown-comment-face ((t (:italic t :slant italic :foreground "#BD4BC4"))))
     (markdown-footnote-face ((t (:weight normal :slant normal :foreground "#babdb6"))))
     (markdown-gfm-checkbox-face ((t (:foreground "#729fcf"))))
     (markdown-header-delimiter-face ((t (:weight normal :slant normal :foreground "#babdb6"))))
     (markdown-header-face ((t (:bold t :foreground "#edd400" :weight bold))))
     (markdown-header-face-1 ((t (:bold t :weight bold :foreground "#edd400"))))
     (markdown-header-face-2 ((t (:bold t :weight bold :foreground "#edd400"))))
     (markdown-header-face-3 ((t (:bold t :weight bold :foreground "#edd400"))))
     (markdown-header-face-4 ((t (:bold t :weight bold :foreground "#edd400"))))
     (markdown-header-face-5 ((t (:bold t :weight bold :foreground "#edd400"))))
     (markdown-header-face-6 ((t (:bold t :weight bold :foreground "#edd400"))))
     (markdown-header-rule-face ((t (:weight normal :slant normal :foreground "#babdb6"))))
     (markdown-highlight-face ((t (:foreground "black" :background "#73d216"))))
     (markdown-inline-code-face ((t (:foreground "#73d216"))))
     (markdown-italic-face ((t (:italic t :foreground "#ef2929" :slant italic))))
     (markdown-language-keyword-face ((t (:bold t :weight bold :foreground "#73d216"))))
     (markdown-line-break-face ((t (:foreground "#73d216" :underline t))))
     (markdown-link-face ((t (:bold t :weight bold :foreground "#729fcf"))))
     (markdown-link-title-face ((t (:italic t :slant italic :foreground "#BD4BC4"))))
     (markdown-list-face ((t (:weight normal :slant normal :foreground "#babdb6"))))
     (markdown-markup-face ((t (:foreground "#babdb6" :slant normal :weight normal))))
     (markdown-math-face ((t (:foreground "#fcaf3e"))))
     (markdown-metadata-key-face ((t (:foreground "#ef2929"))))
     (markdown-metadata-value-face ((t (:foreground "#fcaf3e"))))
     (markdown-missing-link-face ((t (:bold t :weight bold :foreground "#fcaf3e"))))
     (markdown-pre-face ((t (:foreground "#73d216"))))
     (markdown-reference-face ((t (:weight normal :slant normal :foreground "#babdb6"))))
     (markdown-strike-through-face ((t (:foreground "#ef2929" :strike-through t))))
     (markdown-url-face ((t (:foreground "#fcaf3e"))))
     (match ((t (:bold t :background "#e9b96e" :foreground "#0c191C" :weight bold))))
     (matlab-cellbreak-face ((t (:bold t :foreground "Firebrick" :overline t :weight bold))))
     (matlab-cross-function-variable-face ((t (:italic t :bold t :slant italic :weight bold))))
     (matlab-nested-function-keyword-face ((t (:italic t :slant italic))))
     (matlab-region-face ((t (:background "gtk_selection_bg_color" :foreground "gtk_selection_fg_color"))))
     (matlab-simulink-keyword-face ((t (:foreground "ForestGreen" :underline t))))
     (matlab-unterminated-string-face ((t (:foreground "VioletRed4" :underline t))))
     (menu ((t (nil))))
     (message-header-cc ((t (:foreground "#d3d7cf"))))
     (message-header-name ((t (:bold t :weight bold :foreground "#729fcf"))))
     (message-header-newsgroups ((t (:bold t :foreground "#d3d7cf" :weight bold))))
     (message-header-other ((t (:italic t :slant italic :foreground "#d3d7cf"))))
     (message-header-subject ((t (nil))))
     (message-header-to ((t (:bold t :weight bold :foreground "#d3d7cf"))))
     (message-header-xheader ((t (:foreground "#888a85"))))
     (message-mml ((t (:foreground "#8ae234"))))
     (message-separator ((t (:foreground "#204a87"))))
     (minibuffer-prompt ((t (:bold t :foreground "#729fcf" :weight bold))))
     (mm-uu-extract ((t (:background "#2e3436"))))
     (mode-line ((t (:background "#222222" :foreground "green" :box (:line-width 1 :color nil :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :foreground "yellow" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#555753" :foreground "#bbbbbc"))))
     (mouse ((t (nil))))
     (next-error ((t (:background "#0c191C"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (org-agenda-calendar-event ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeec" :stipple nil :height 98))))
     (org-agenda-calendar-sexp ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeec" :stipple nil :height 98))))
     (org-agenda-clocking ((t (:background "#204a87"))))
     (org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "#000000" :height 98))))
     (org-agenda-current-time ((t (:foreground "#babdb6"))))
     (org-agenda-date ((t (:foreground "#fce94f" :height 1.2))))
     (org-agenda-date-tc ((t (:foreground "#c4a000" :height 1.2))))
     (org-agenda-date-today ((t (:bold t :foreground "#edd400" :weight bold :height 1.56))))
     (org-agenda-date-weekend ((t (:bold t :foreground "#ef2929" :weight bold :height 1.2))))
     (org-agenda-diary ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeec" :stipple nil :height 98))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (nil))))
     (org-agenda-filter-category ((t (:box (:line-width 1 :color nil :style released-button) :foreground "green" :background "#222222"))))
     (org-agenda-filter-tags ((t (:box (:line-width 1 :color nil :style released-button) :foreground "green" :background "#222222"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "#babdb6"))))
     (org-block ((t (:foreground "#babdb6"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:italic t :foreground "#BD4BC4" :slant italic))))
     (org-block-end-line ((t (:italic t :foreground "#BD4BC4" :slant italic))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "#4e9a06"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "#cc0000"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "#babdb6"))))
     (org-column ((t (:background "#000000" :strike-through nil :underline nil :slant normal :weight normal :height 98 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "#e9b96e"))))
     (org-date-selected ((t (:background "Pink"))))
     (org-default ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeec" :stipple nil :height 98))))
     (org-document-info ((t (:italic t :foreground "#729fcf" :slant italic))))
     (org-document-info-keyword ((t (:foreground "#babdb6"))))
     (org-document-title ((t (:bold t :foreground "#729fcf" :weight bold :height 1.4))))
     (org-done ((t (:bold t :foreground "#4e9a06" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-habit-alert-ready-future-face ((t (:background "#ce5c00"))))
     (org-habit-clear-face ((t (:background "#3465a4"))))
     (org-habit-clear-future-face ((t (:background "#204a87"))))
     (org-habit-overdue-face ((t (:background "#a40000"))))
     (org-habit-overdue-future-face ((t (:background "#a40000"))))
     (org-habit-ready-face ((t (:background "#73d216" :foreground "#0c191C"))))
     (org-habit-ready-future-face ((t (:background "#4e9a06"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     ;; (org-hide ((t (:foreground "#130015"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "#729fcf" :weight bold :height 1.3))))
     (org-level-2 ((t (:bold t :foreground "#8ae234" :weight bold :height 1.2))))
     (org-level-3 ((t (:bold t :foreground "#fce94f" :weight bold :height 1.1))))
     (org-level-4 ((t (:bold t :foreground "#ad7fa8" :weight bold))))
     (org-level-5 ((t (:bold t :foreground "#e9b96e" :weight bold))))
     (org-level-6 ((t (:bold t :foreground "#fcaf3e" :weight bold))))
     (org-level-7 ((t (:bold t :foreground "#3465a4" :weight bold))))
     (org-level-8 ((t (:bold t :foreground "#73d216" :weight bold))))
     (org-link ((t (:foreground "#729fcf"))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-meta-line ((t (:italic t :slant italic :foreground "#BD4BC4"))))
     (org-mode-line-clock ((t (nil))))
     (org-mode-line-clock-overrun ((t (:foreground "#ef2929"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "#babdb6"))))
     (org-scheduled ((t (:foreground "#73d216"))))
     (org-scheduled-previously ((t (:foreground "#f57900"))))
     (org-scheduled-today ((t (:foreground "#8ae234"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:bold t :foreground "#ef2929" :weight bold))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "#babdb6"))))
     (org-todo ((t (:bold t :foreground "#cc0000" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "#babdb6"))))
     (org-verse ((t (:foreground "#babdb6"))))
     (org-warning ((t (:bold t :weight bold :foreground "#fcaf3e"))))
     (outline-1 ((t (:bold t :weight bold :foreground "#edd400"))))
     (outline-2 ((t (:foreground "#ef2929"))))
     (outline-3 ((t (:bold t :weight bold :foreground "#729fcf"))))
     (outline-4 ((t (:italic t :slant italic :foreground "#BD4BC4"))))
     (outline-5 ((t (:bold t :weight bold :foreground "#73d216"))))
     (outline-6 ((t (:foreground "#73d216"))))
     (outline-7 ((t (:foreground "#729fcf"))))
     (outline-8 ((t (:foreground "#fcaf3e"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:foreground "black" :background "lightgray"))))
     (popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-summary-face ((t (:foreground "dimgray" :background "lightgray"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-summary-face ((t (:background "lightgray" :foreground "dimgray"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (rainbow-delimiters-depth-1-face ((t (:foreground "#729fcf"))))
     (rainbow-delimiters-depth-10-face ((t (:foreground "#75507b"))))
     (rainbow-delimiters-depth-11-face ((t (:foreground "#c17d11"))))
     (rainbow-delimiters-depth-12-face ((t (:foreground "#729fcf"))))
     (rainbow-delimiters-depth-2-face ((t (:foreground "#8ae234"))))
     (rainbow-delimiters-depth-3-face ((t (:foreground "#fce94f"))))
     (rainbow-delimiters-depth-4-face ((t (:foreground "#ad7fa8"))))
     (rainbow-delimiters-depth-5-face ((t (:foreground "#e9b96e"))))
     (rainbow-delimiters-depth-6-face ((t (:foreground "#fcaf3e"))))
     (rainbow-delimiters-depth-7-face ((t (:foreground "#3465a4"))))
     (rainbow-delimiters-depth-8-face ((t (:foreground "#73d216"))))
     (rainbow-delimiters-depth-9-face ((t (:foreground "#f57900"))))
     (region ((t (:background "#0c191C"))))
     (rst-level-1-face ((t (:foreground "#729fcf" :height 1.3))))
     (rst-level-2-face ((t (:foreground "#8ae234" :height 1.2))))
     (rst-level-3-face ((t (:foreground "#fce94f" :height 1.1))))
     (rst-level-4-face ((t (:foreground "#ad7fa8"))))
     (rst-level-5-face ((t (:foreground "#e9b96e"))))
     (rst-level-6-face ((t (:foreground "#fcaf3e"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "#204a87"))))
     (sh-escaped-newline ((t (:foreground "#fcaf3e"))))
     (sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "#babdb6"))))
     (show-paren-match ((t (:background "#4e9a06"))))
     (show-paren-mismatch ((t (:background "#a40000"))))
     (spam ((t (:background "#0c191C" :foreground "#f57900"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "#0c191C" :foreground "#eeeeec"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-func ((t (:foreground "#729fcf"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "#babdb6"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-bold ((t (:bold t :foreground "#edd400" :weight bold))))
     (woman-italic ((t (:foreground "cyan"))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:background "#0c191C")))))))
(add-to-list 'color-themes '(paul-themes-naquadah2  "Naquadah2" "Paul Ozog <pjozog@gmail.com>"))

(color-theme-initialize)

(provide 'paul-themes)
