#!/bin/sh

if test -n "$1"; then
    echo "Syntax: i3-session"
  exit
fi

# Clean up after GDM
xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
      -remove _NET_DESKTOP_NAMES \
      -remove _NET_CURRENT_DESKTOP 2> /dev/null

# Set up the environment
A="${XDG_CONFIG_HOME:-"$HOME/.config"}/autostart.sh"
test -r $A && . $A

# Run Awesome, and have it run the autostart stuff
exec /usr/bin/i3
